In [1]:
import pandas as pd
iris = pd.read_csv("C:/Users/Admin/Documents/Datasets/iris.csv")
iris.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa

In [2]:
import numpy as np
iris.Species = iris.Species.astype("category")
iris["Species1"] = np.repeat([0, 1, 2], 50) # for first 50 observations = 0; for next 50 = 1; for last 50 = 2

In [3]:
iris.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  \
0           1           5.1          3.5           1.4          0.2  setosa   
1           2           4.9          3.0           1.4          0.2  setosa   
2           3           4.7          3.2           1.3          0.2  setosa   
3           4           4.6          3.1           1.5          0.2  setosa   
4           5           5.0          3.6           1.4          0.2  setosa   

   Species1  
0         0  
1         0  
2         0  
3         0  
4         0

In [16]:
X = iris.iloc[:, :4]
y = iris.iloc[:, -1]
print(X.head())
print(y.tail())

   Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length
0           1           5.1          3.5           1.4
1           2           4.9          3.0           1.4
2           3           4.7          3.2           1.3
3           4           4.6          3.1           1.5
4           5           5.0          3.6           1.4
145    2
146    2
147    2
148    2
149    2
Name: Species1, dtype: int32


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [9]:
# import Neural Network libraries (MLP - MultiLayerPerceptron)
from sklearn.neural_network import MLPClassifier
# from sklearn.metrics import 

In [19]:
# Classification
# activation: 'logistic', 'tanh', 'relu', 'identity'(f(x)=x  sometimes we need it, but, mostly not)
nnclf = MLPClassifier(solver="sgd", activation="logistic",
                     hidden_layer_sizes=(5),
                     learning_rate_init=0.05,
                     max_iter=2000,
                     random_state=0).fit(X_train, y_train)


In [20]:
print("Iris Data Set")
print("Accuracy of NN classifier on train set: {:.3f}".format(nnclf.score(X_train, y_train)))
print("Accuracy of NN classifier on test set: {:.3f}".format(nnclf.score(X_test, y_test)))

Iris Data Set
Accuracy of NN classifier on train set: 0.429
Accuracy of NN classifier on test set: 0.289


In [21]:
print(nnclf.predict_proba(X_test))
print(nnclf.predict(X_test))

[[0.31493471 0.31382249 0.37124279]
 [0.31551861 0.31354139 0.37094   ]
 [0.31588612 0.31339164 0.37072224]
 [0.31449919 0.31403438 0.37146644]
 [0.41713686 0.24224624 0.3406169 ]
 [0.31462119 0.31397503 0.37140378]
 [0.31676692 0.31294841 0.37028467]
 [0.31477753 0.31389903 0.37132343]
 [0.31482243 0.31387748 0.37130009]
 [0.31520645 0.31369093 0.37110262]
 [0.31477987 0.31389782 0.37132231]
 [0.31493319 0.31383296 0.37123385]
 [0.31503382 0.31377488 0.3711913 ]
 [0.31498472 0.31380593 0.37120935]
 [0.31503119 0.31377789 0.37119092]
 [0.31672725 0.31297674 0.37029601]
 [0.31506596 0.31375892 0.37117512]
 [0.31533684 0.31362694 0.37103622]
 [0.31732654 0.3126705  0.37000296]
 [0.31845216 0.3117948  0.36975305]
 [0.31501431 0.31378377 0.37120192]
 [0.31520452 0.31369273 0.37110275]
 [0.31671552 0.31315994 0.37012454]
 [0.36616094 0.27779486 0.3560442 ]
 [0.31486034 0.31385867 0.37128099]
 [0.31740881 0.3127978  0.36979339]
 [0.31610351 0.31326423 0.37063227]
 [0.31499818 0.31379163 0.37

In [22]:
print("Classes for y: ", nnclf.classes_)
print("Activation function at output layer: ", nnclf.out_activation_)
print("Number of Layers: ", nnclf.n_layers_)
print("Number of Outputs: ", nnclf.n_outputs_)
print("Number of iterations for convergence: ", nnclf.n_iter_)
print("\nWeights matrix:\n", nnclf.coefs_)
print("\nBiases:\n", nnclf.intercepts_)

Classes for y:  [0 1 2]
Activation function at output layer:  softmax
Number of Layers:  3
Number of Outputs:  3
Number of iterations for convergence:  37

Weights matrix:
 [array([[-0.52998925,  0.36111599,  0.18796543,  0.00311888, -0.13948093],
       [ 0.44673126,  0.07644852,  0.42740621,  0.35455554, -0.15755169],
       [ 0.52004205,  0.11969676,  0.1036916 ,  0.33844122, -0.43805413],
       [-0.36014659, -0.41289383,  0.33042912,  0.25379574,  0.33733733]]), array([[ 0.76893892, -0.4769718 , -0.06402685],
       [-0.0612938 , -0.05300824, -0.18462821],
       [ 0.35106413, -0.07039123,  0.01814119],
       [-0.40492702,  0.08538132,  0.06806998],
       [ 0.20906486,  0.41012578,  0.1233021 ]])]

Biases:
 [array([ 0.51745775,  0.3094561 , -0.02450144,  0.24647198, -0.36974329]), array([-0.02666635, -0.10373138,  0.12456878])]


In [31]:
# keras

In [32]:
# Keras is built in Python and on top of TensorFlow 2.0
# Keras is a neural network library while 
# TensorFlow is the open source library for a number of tasks in machine learning.
# Both frameworks provide high-level APIs for building and training models with ease.

In [33]:
import tensorflow as tf
import keras

In [34]:
# Creating MLP in Keras
# Sequential function groups a linear stack of Layers into a keras model
# Sequential model provides training and inference features onthis model
from keras import Sequential
# A dense layer is just a regular layer of neurons in a neural network.
# Each neuron receives input from all the neurons in the previous layer,
# thus, densely connected.
from keras.layers import Dense

In [35]:
# create model
model= Sequential()

In [36]:
# In first Dense layer, the dimension of input layer can be given
model.add(Dense(6, input_dim=4, activation='sigmoid', name='HL1'))
model.add(Dense(3, activation='relu', name='HL2'))
model.add(Dense(3, activation='softmax', name='OL'))

In [37]:
# initialized weights
print([layer.get_weights() for layer in model.layers])
# print(model.weights)

[[array([[-0.10976148, -0.724444  , -0.65626395,  0.03619325, -0.65522605,
        -0.1286413 ],
       [ 0.17736149,  0.43961787,  0.24760103,  0.6833154 , -0.5694884 ,
        -0.05032927],
       [ 0.7553977 ,  0.49032164, -0.15084296, -0.49373895, -0.06490886,
        -0.58194923],
       [-0.04479241, -0.69237113,  0.51764345,  0.35794258, -0.16833794,
        -0.1721471 ]], dtype=float32), array([0., 0., 0., 0., 0., 0.], dtype=float32)], [array([[ 0.74488175, -0.54191613, -0.5168633 ],
       [ 0.5770873 , -0.7906784 ,  0.7854657 ],
       [-0.07608813,  0.16662508,  0.24417436],
       [-0.26737082, -0.01518101, -0.74629897],
       [-0.47043985, -0.811698  ,  0.08906704],
       [-0.28696412,  0.44837713, -0.6783608 ]], dtype=float32), array([0., 0., 0.], dtype=float32)], [array([[ 0.9990339 , -0.7179899 , -0.3273058 ],
       [-0.08639574,  0.4291401 , -0.8756099 ],
       [ 0.6613624 ,  0.17456937, -0.8141086 ]], dtype=float32), array([0., 0., 0.], dtype=float32)]]


In [38]:
print("Input layer shape: ", model.input_shape)
print("Output layer shape: ", model.output_shape)

Input layer shape:  (None, 4)
Output layer shape:  (None, 3)


In [39]:
from keras import metrics
from keras.metrics import Precision, Recall, AUC

In [40]:
# Compile model
# Compile defines the loss function, the optimizer and the metrics
# You need a compiled model to train because training uses the loss function and optimizer
# model.compile(loss='mse', optimizer='sgd',
#              metrics=['accuracy', AUC, Precision, Recall])

model.compile(loss='mse', optimizer='sgd',
              metrics=['accuracy', tf.keras.metrics.AUC(), tf.keras.metrics.Precision(),
                      tf.keras.metrics.Recall()])