In [ ]:
import pandas as pd
iris = pd.read_csv("C:/Users/Admin/Documents/Datasets/iris.csv")
iris.head()

In [22]:
import numpy as np
iris.Species = iris.Species.astype("category")
iris["Species1"] = np.repeat([0, 1, 2], 50) # for first 50 observations = 0; for next 50 = 1; for last 50 = 2

In [23]:
iris.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  \
0           1           5.1          3.5           1.4          0.2  setosa   
1           2           4.9          3.0           1.4          0.2  setosa   
2           3           4.7          3.2           1.3          0.2  setosa   
3           4           4.6          3.1           1.5          0.2  setosa   
4           5           5.0          3.6           1.4          0.2  setosa   

   Species1  
0         0  
1         0  
2         0  
3         0  
4         0

In [24]:
X = iris.iloc[:, :4]
y = iris.iloc[:, -1]
print(X.head())
print(y.head())

   Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length
0           1           5.1          3.5           1.4
1           2           4.9          3.0           1.4
2           3           4.7          3.2           1.3
3           4           4.6          3.1           1.5
4           5           5.0          3.6           1.4
0    0
1    0
2    0
3    0
4    0
Name: Species1, dtype: int32


In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [26]:
# import Neural Network libraries
from sklearn.neural_network import MLPClassifier
# from sklearn.metrics import 

In [27]:
# Classification
# activation: 'logistic', 'tanh', 'relu', 'identity'(f(x)=x  sometimes we need it, but, mostly not)
nnclf = MLPClassifier(solver="sgd", activation="logistic",
                     hidden_layer_sizes=(5),
                     learning_rate_init=0.05,
                     max_iter=2000,
                     random_state=0).fit(X_train, y_train)


In [28]:
print("Iris Data Set")
print("Accuracy of NN classifier on train set: {:.3f}".format(nnclf.score(X_train, y_train)))
print("Accuracy of NN classifier on test set: {:.3f}".format(nnclf.score(X_test, y_test)))

Iris Data Set
Accuracy of NN classifier on train set: 0.429
Accuracy of NN classifier on test set: 0.289


In [29]:
print(nnclf.predict_proba(X_test))
print(nnclf.predict(X_test))

[[0.31493471 0.31382249 0.37124279]
 [0.31551861 0.31354139 0.37094   ]
 [0.31588612 0.31339164 0.37072224]
 [0.31449919 0.31403438 0.37146644]
 [0.41713686 0.24224624 0.3406169 ]
 [0.31462119 0.31397503 0.37140378]
 [0.31676692 0.31294841 0.37028467]
 [0.31477753 0.31389903 0.37132343]
 [0.31482243 0.31387748 0.37130009]
 [0.31520645 0.31369093 0.37110262]
 [0.31477987 0.31389782 0.37132231]
 [0.31493319 0.31383296 0.37123385]
 [0.31503382 0.31377488 0.3711913 ]
 [0.31498472 0.31380593 0.37120935]
 [0.31503119 0.31377789 0.37119092]
 [0.31672725 0.31297674 0.37029601]
 [0.31506596 0.31375892 0.37117512]
 [0.31533684 0.31362694 0.37103622]
 [0.31732654 0.3126705  0.37000296]
 [0.31845216 0.3117948  0.36975305]
 [0.31501431 0.31378377 0.37120192]
 [0.31520452 0.31369273 0.37110275]
 [0.31671552 0.31315994 0.37012454]
 [0.36616094 0.27779486 0.3560442 ]
 [0.31486034 0.31385867 0.37128099]
 [0.31740881 0.3127978  0.36979339]
 [0.31610351 0.31326423 0.37063227]
 [0.31499818 0.31379163 0.37

In [30]:
print("Classes for y: ", nnclf.classes_)
print("Activation function at output layer: ", nnclf.out_activation_)
print("Number of Layers: ", nnclf.n_layers_)
print("Number of Outputs: ", nnclf.n_outputs_)
print("Number of iterations for convergence: ", nnclf.n_iter_)
print("\nWeights matrix:\n", nnclf.coefs_)
print("\nBiases:\n", nnclf.intercepts_)

Classes for y:  [0 1 2]
Activation function at output layer:  softmax
Number of Layers:  3
Number of Outputs:  3
Number of iterations for convergence:  37

Weights matrix:
 [array([[-0.52998925,  0.36111599,  0.18796543,  0.00311888, -0.13948093],
       [ 0.44673126,  0.07644852,  0.42740621,  0.35455554, -0.15755169],
       [ 0.52004205,  0.11969676,  0.1036916 ,  0.33844122, -0.43805413],
       [-0.36014659, -0.41289383,  0.33042912,  0.25379574,  0.33733733]]), array([[ 0.76893892, -0.4769718 , -0.06402685],
       [-0.0612938 , -0.05300824, -0.18462821],
       [ 0.35106413, -0.07039123,  0.01814119],
       [-0.40492702,  0.08538132,  0.06806998],
       [ 0.20906486,  0.41012578,  0.1233021 ]])]

Biases:
 [array([ 0.51745775,  0.3094561 , -0.02450144,  0.24647198, -0.36974329]), array([-0.02666635, -0.10373138,  0.12456878])]


In [31]:
# keras

In [32]:
# Keras is built in Python and on top of TensorFlow 2.0
# Keras is a neural network library while 
# TensorFlow is the open source library for a number of tasks in machine learning.
# Both frameworks provide high-level APIs for building and training models with ease.

In [33]:
import tensorflow as tf
import keras

In [34]:
# Creating MLP in Keras
# Sequential function groups a linear stack of Layers into a keras model
# Sequential model provides training and inference features onthis model
from keras import Sequential
# A dense layer is just a regular layer of neurons in a neural network.
# Each neuron receives input from all the neurons in the previous layer,
# thus, densely connected.
from keras.layers import Dense

In [35]:
# create model
model= Sequential()

In [36]:
# In first Dense layer, the dimension of input layer can be given
model.add(Dense(6, input_dim=4, activation='sigmoid', name='HL1'))
model.add(Dense(3, activation='relu', name='HL2'))
model.add(Dense(3, activation='softmax', name='OL'))

In [37]:
# initialized weights
print([layer.get_weights() for layer in model.layers])
# print(model.weights)

[[array([[-0.10976148, -0.724444  , -0.65626395,  0.03619325, -0.65522605,
        -0.1286413 ],
       [ 0.17736149,  0.43961787,  0.24760103,  0.6833154 , -0.5694884 ,
        -0.05032927],
       [ 0.7553977 ,  0.49032164, -0.15084296, -0.49373895, -0.06490886,
        -0.58194923],
       [-0.04479241, -0.69237113,  0.51764345,  0.35794258, -0.16833794,
        -0.1721471 ]], dtype=float32), array([0., 0., 0., 0., 0., 0.], dtype=float32)], [array([[ 0.74488175, -0.54191613, -0.5168633 ],
       [ 0.5770873 , -0.7906784 ,  0.7854657 ],
       [-0.07608813,  0.16662508,  0.24417436],
       [-0.26737082, -0.01518101, -0.74629897],
       [-0.47043985, -0.811698  ,  0.08906704],
       [-0.28696412,  0.44837713, -0.6783608 ]], dtype=float32), array([0., 0., 0.], dtype=float32)], [array([[ 0.9990339 , -0.7179899 , -0.3273058 ],
       [-0.08639574,  0.4291401 , -0.8756099 ],
       [ 0.6613624 ,  0.17456937, -0.8141086 ]], dtype=float32), array([0., 0., 0.], dtype=float32)]]


In [38]:
print("Input layer shape: ", model.input_shape)
print("Output layer shape: ", model.output_shape)

Input layer shape:  (None, 4)
Output layer shape:  (None, 3)


In [39]:
from keras import metrics
from keras.metrics import Precision, Recall, AUC

In [40]:
# Compile model
# Compile defines the loss function, the optimizer and the metrics
# You need a compiled model to train because training uses the loss function and optimizer
# model.compile(loss='mse', optimizer='sgd',
#              metrics=['accuracy', AUC, Precision, Recall])

model.compile(loss='mse', optimizer='sgd',
              metrics=['accuracy', tf.keras.metrics.AUC(), tf.keras.metrics.Precision(),
                      tf.keras.metrics.Recall()])

# 2020-JUN-7TH

In [10]:
import pandas as pd
cars = pd.read_csv("C:/Users/Admin/Documents/Datasets/mtcars.csv")
cars.set_index('Unnamed: 0', inplace = True)
# cars['cyl'] = cars['cyl'].astype('category')
# cars['am'] = cars['am'].astype('category')

y = cars['mpg']
X = cars.iloc[:,2:11]

print(X.head())
print(y.head())


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)


                    disp   hp  drat     wt   qsec  vs  am  gear  carb
Unnamed: 0                                                           
Mazda RX4          160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag      160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710         108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive     258.0  110  3.08  3.215  19.44   1   0     3     1
Hornet Sportabout  360.0  175  3.15  3.440  17.02   0   0     3     2
Unnamed: 0
Mazda RX4            21.0
Mazda RX4 Wag        21.0
Datsun 710           22.8
Hornet 4 Drive       21.4
Hornet Sportabout    18.7
Name: mpg, dtype: float64


In [2]:
# Effect of Normalizing input value

from sklearn.preprocessing import StandardScaler
X_scaled = StandardScaler().fit(X_train)
X_scaled_train = X_scaled.transform(X_train)
X_scaled_test = X_scaled.transform(X_test)
# scaled values
print(X_scaled_train[:2])

[[-0.82316132 -0.62584351  0.20011909 -0.70870565  1.07038511  1.
  -0.84515425 -0.9701425  -1.02105494]
 [ 0.53669245  0.58452568 -1.00537917  0.82095857 -0.00782282 -1.
  -0.84515425 -0.9701425   0.14586499]]


In [2]:
from sklearn.neural_network import MLPRegressor

# sgd,relu,[70,70],learning_rate_init = 0.1 diverges
nnreg = MLPRegressor(solver = 'sgd', activation = 'relu',
                    hidden_layer_sizes = [70,70],
                    learning_rate = 'constant',
                    learning_rate_init = 0.00001,
                    max_iter = 6000,
#                     alpha=
                    random_state=0).fit(X_scaled_train, y_train)

NameError: name 'X_scaled_train' is not defined

In [16]:
print('Cars Data Set')
print('R2 on training set: {:.3f}'
    .format(nnreg.score(X_scaled_train, y_train)))
print('R2 on test set: {:.3f}'
    .format(nnreg.score(X_scaled_test, y_test)))

Cars Data Set
R2 on training set: 0.928
R2 on test set: 0.754


In [17]:
# Grid Search
from sklearn.model_selection import GridSearchCV

# Total number of models in Grid = 3* 3 * 5 * 3 = 135
solv = ['lbfgs','adam','sgd']
act = ['logistic','tanh','relu']
lr_init = [0.1,0.05,0.01,0.005]#,0.001] 
hidden_layer_sz = [(7),(7,7),(7,7,7)]

param_grid = {'solver': solv,
              'activation': act,
              'learning_rate_init': lr_init,
              'hidden_layer_sizes': hidden_layer_sz }

grid_search = GridSearchCV(MLPRegressor(learning_rate = 'constant',
                                                    max_iter = 8000,
                                                    random_state=30),
                           param_grid, cv=3, return_train_score=True,
                           scoring = ['neg_mean_squared_error','r2'],
                           refit = 'r2')
#                          scoring = ['precision','recall','f1','auc'],
#                          refit = 'f1')

grid_models = grid_search.fit(X_train, y_train)

In [6]:
# scoring parameters
grid_models.scorer_

{'neg_mean_squared_error': make_scorer(mean_squared_error, greater_is_better=False),
 'r2': make_scorer(r2_score)}

In [7]:
# best parameters
grid_models.best_params_

{'activation': 'relu',
 'hidden_layer_sizes': (7, 7, 7),
 'learning_rate_init': 0.1,
 'solver': 'adam'}

In [8]:
# best estimators
grid_models.best_estimator_

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(7, 7, 7), learning_rate='constant',
             learning_rate_init=0.1, max_fun=15000, max_iter=8000, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=30, shuffle=True, solver='adam', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [9]:
# mean test r2 (mean of all folds)
grid_models.best_score_

0.779579463198389

In [62]:
# fitting on training data
grid_models.score(X_train, y_train)

0.6271057248958436

In [63]:
# fitting on test data
grid_models.score(X_test, y_test)

0.4552296477553893

In [44]:
# best estimators
grid_models.best_estimator_

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=7, learning_rate='constant',
             learning_rate_init=0.1, max_fun=15000, max_iter=8000, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=0, shuffle=True, solver='lbfgs', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [45]:
# mean test r2 (mean of all folds)
grid_models.best_score_

0.7872762187459511

In [46]:
# fitting on training data
grid_models.score(X_train, y_train)

0.9406414936836227

In [47]:
# fitting on test data
grid_models.score(X_test, y_test)

0.2716990824404726

In [48]:
# results for all the models, imported into dataframe
cv_results = pd.DataFrame(grid_models.cv_results_)
cv_results.shape

(135, 31)

In [49]:
cv_results.head(2)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.094382      0.119539         0.001344        0.000620   
1       0.026209      0.003698         0.002239        0.000905   

  param_activation param_hidden_layer_sizes param_learning_rate_init  \
0         logistic                        7                      0.1   
1         logistic                        7                      0.1   

  param_solver                                             params  \
0        lbfgs  {'activation': 'logistic', 'hidden_layer_sizes...   
1         adam  {'activation': 'logistic', 'hidden_layer_sizes...   

   split0_test_neg_mean_squared_error  ...  split1_test_r2  split2_test_r2  \
0                          -32.059644  ...   -1.759096e-02       -0.077878   
1                          -31.660795  ...   -6.940798e-07       -0.183036   

   mean_test_r2  std_test_r2  rank_test_r2  split0_train_r2  split1_train_r2  \
0     -0.036539     0.029264            80    -1.300429e-07    -1.950328e-08   
1     -0.061523     0.085925            97    -2.023084e-02    -2.524962e-02   

   split2_train_r2  mean_train_r2  std_train_r2  
0    -7.915540e-09  -5.248725e-08  5.504381e-08  
1    -1.801163e-02  -2.116403e-02  3.027680e-03  

[2 rows x 31 columns]

In [50]:
cv_results.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_activation', 'param_hidden_layer_sizes',
       'param_learning_rate_init', 'param_solver', 'params',
       'split0_test_neg_mean_squared_error',
       'split1_test_neg_mean_squared_error',
       'split2_test_neg_mean_squared_error',
       'mean_test_neg_mean_squared_error', 'std_test_neg_mean_squared_error',
       'rank_test_neg_mean_squared_error',
       'split0_train_neg_mean_squared_error',
       'split1_train_neg_mean_squared_error',
       'split2_train_neg_mean_squared_error',
       'mean_train_neg_mean_squared_error', 'std_train_neg_mean_squared_error',
       'split0_test_r2', 'split1_test_r2', 'split2_test_r2', 'mean_test_r2',
       'std_test_r2', 'rank_test_r2', 'split0_train_r2', 'split1_train_r2',
       'split2_train_r2', 'mean_train_r2', 'std_train_r2'],
      dtype='object')

In [51]:
grid_models.best_index_

90

In [52]:
cv_results.loc[grid_models.best_index_,]

mean_fit_time                                                                    0.16659
std_fit_time                                                                   0.0763769
mean_score_time                                                               0.00323025
std_score_time                                                                0.00317926
param_activation                                                                    relu
param_hidden_layer_sizes                                                               7
param_learning_rate_init                                                             0.1
param_solver                                                                       lbfgs
params                                 {'activation': 'relu', 'hidden_layer_sizes': 7...
split0_test_neg_mean_squared_error                                              -9.98572
split1_test_neg_mean_squared_error                                              -7.60114
split2_test_neg_mean_

In [53]:
# Best result of scoring parameters
print('index of best model in data frame', grid_models.best_index_)
print('\nBest result of scoring parameters\n')
print(cv_results.loc[grid_models.best_index_, 
                     ['mean_train_neg_mean_squared_error','mean_test_neg_mean_squared_error']],'\n')
print(cv_results.loc[grid_models.best_index_, 
                     ['mean_train_r2','mean_test_r2']])
print('\nNote: Test result is on cross validation test rows')

index of best model in data frame 90

Best result of scoring parameters

mean_train_neg_mean_squared_error   -1.47368
mean_test_neg_mean_squared_error    -7.48125
Name: 90, dtype: object 

mean_train_r2    0.958602
mean_test_r2     0.787276
Name: 90, dtype: object

Note: Test result is on cross validation test rows


In [54]:
grid_models.predict(X)

array([21.34946705, 20.84060623, 26.96461804, 20.73011831, 18.47717302,
       19.03385681, 14.38421352, 22.34521078, 23.94715686, 18.53838783,
       18.87333782, 13.4535887 , 14.66054645, 14.72277177, 12.72599627,
       11.80027882, 11.63238393, 29.77176693, 32.12241798, 31.78337639,
       21.81134188, 16.74005556, 17.74725734, 14.12927304, 17.95338961,
       30.17800082, 28.48378045, 29.89764245, 24.02655125, 19.1610249 ,
       14.9857022 , 24.32073741])

# RANDOMIZED SEARCH

In [64]:
# Randomized Search
from sklearn.model_selection import RandomizedSearchCV

In [83]:
def lr_init_fn(n,low,high):
    print(np.log10(low))
    print(np.log10(high))
    print(np.log10(high) - np.log10(low))
    print(*np.random.sample(n))
    print((np.log10(high) - np.log10(low))*np.random.sample(n))
    print(np.log10(low)+(np.log10(high) - np.log10(low))*np.random.sample(n))
    
    return(10**(np.log10(low)+(np.log10(high) - np.log10(low))*np.random.sample(n)))

def hidden_layer_fn(n_instance,n_layers,low,high,):
    hid_layer_list = []
    for i in range(n_instance):
        hid_layer = []
        for j in range(n_layers):
            hid_layer.append(np.random.randint(low, high))
        hid_layer_list.append(hid_layer)
    return hid_layer_list

In [84]:
import numpy as np

# n_iter: The number of parameter settings that are tried

solv = ['lbfgs','adam','sgd']
act = ['logistic','tanh','relu']
lr_init = lr_init_fn(25,0.0001,0.1)
hidden_layer_sz = hidden_layer_fn(5,1,3,10)+hidden_layer_fn(4,2,3,10)+hidden_layer_fn(3,3,3,10)


param_grid = {'solver': solv,
              'activation': act,
              'learning_rate_init': lr_init,
              'hidden_layer_sizes': hidden_layer_sz}

-4.0
-1.0
3.0
0.8242275467544284 0.8948692698106464 0.7806560832302964 0.7202966647421338 0.6973579325314073 0.46283023317604854 0.13504097473397936 0.031029160895352348 0.1578341287842756 0.4764165680892759 0.05477676040726476 0.048908416149630596 0.03261199227399847 0.489169413854727 0.23434372107199708 0.385353794379822 0.5602753210292067 0.08005481341687115 0.9473046818342771 0.7395323489584626 0.34217111191777294 0.26762143433466046 0.8297042112974878 0.8692325701171996 0.2701956060630417
[2.04610972 1.93053458 2.26550282 2.03497509 2.27094348 1.07079412
 1.02633739 2.78242682 2.14941555 1.74289827 1.26491369 1.82431921
 2.26179739 1.51822322 1.9746627  0.27036151 0.42330746 1.37744199
 1.99989156 2.65406944 0.78394214 2.43220451 2.98098078 1.66281143
 2.21523515]
[-2.54473637 -1.49088734 -3.83271837 -2.71135391 -2.68533998 -2.8757275
 -3.06145852 -2.23530669 -2.29004101 -3.67176334 -2.38303507 -3.48778709
 -1.96787776 -2.22558661 -1.87822608 -2.75666793 -2.1212467  -3.00040583
 -

In [68]:
lr_init

array([0.00043842, 0.0518229 , 0.00022166, 0.00670933, 0.01974964,
       0.00081215, 0.04245316, 0.00052137, 0.0097197 , 0.00012665,
       0.00900137, 0.0002778 , 0.00011307, 0.00014487, 0.00017283,
       0.01224821, 0.0386499 , 0.01309838, 0.00104719, 0.0029726 ,
       0.09206452, 0.00051526, 0.00013265, 0.00021981, 0.01362494])

In [69]:
hidden_layer_sz

[[8],
 [3],
 [6],
 [8],
 [4],
 [5, 4],
 [5, 7],
 [4, 9],
 [8, 7],
 [9, 7, 3],
 [4, 9, 5],
 [3, 6, 8]]

In [70]:
random_search = RandomizedSearchCV(MLPRegressor(learning_rate = 'constant',
                                                max_iter = 8000,
                                                random_state=0),
                           param_grid, cv=3, return_train_score=True,
                           scoring = ['neg_mean_squared_error','r2'],
                           n_iter = 30,
                           refit = 'r2')

random_models = random_search.fit(X_train, y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (8000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (8000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (8000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (8000) reached and the optimization hasn't converged yet.
  % self.max_iter, 

In [71]:
# results for all the models, imported into dataframe
cv_results = pd.DataFrame(random_models.cv_results_)
cv_results.shape

(30, 31)

In [72]:
cv_results

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_solver  \
0        0.013145      0.010160         0.001331    4.702464e-04        lbfgs   
1        0.012300      0.006163         0.001661    4.693590e-04          sgd   
2        7.048415      1.913177         0.001664    9.402684e-04         adam   
3        0.017181      0.006679         0.001540    7.690395e-04          sgd   
4        0.192254      0.029827         0.004987    3.549814e-03          sgd   
5        0.005659      0.001234         0.001323    4.601874e-04        lbfgs   
6        0.116542      0.016160         0.001994    8.142961e-04          sgd   
7        4.676124      0.522935         0.003656    9.394814e-04         adam   
8        3.392203      0.303768         0.001995    1.362676e-06         adam   
9        0.007983      0.002154         0.001671    4.762555e-04        lbfgs   
10       0.153572      0.012231         0.002437    6.270889e-04          sgd   
11       0.010964      0.002825         0.002326    4.708648e-04          sgd   
12       3.772509      0.947370         0.001995    4.126471e-06         adam   
13       0.350070      0.029216         0.002335    4.648953e-04         adam   
14       0.446067      0.366413         0.003990    2.820860e-03        lbfgs   
15       0.240349      0.323756         0.001663    4.713723e-04        lbfgs   
16       0.006649      0.001243         0.002660    9.397623e-04        lbfgs   
17       0.251665      0.105856         0.001663    4.700781e-04        lbfgs   
18       0.005041      0.000749         0.001330    4.698531e-04        lbfgs   
19       3.596933      0.454646         0.000988    1.264443e-05         adam   
20       0.004986      0.000815         0.001330    4.695725e-04        lbfgs   
21       1.464618      1.370293         0.001996    8.104673e-07        lbfgs   
22       4.843465      0.898607         0.007316    5.545802e-03         adam   
23       1.222103      0.605734         0.002001    8.387305e-06         adam   
24       1.609463      0.025418         0.001330    4.697970e-04         adam   
25       0.450720      0.140142         0.002661    1.695950e-03          sgd   
26       0.031112      0.003201         0.002327    4.704714e-04          sgd   
27       0.036244      0.008469         0.003788    5.850231e-04          sgd   
28       5.888118      1.134072         0.002327    4.697972e-04         adam   
29       0.009972      0.001629         0.001879    6.768804e-04          sgd   

   param_learning_rate_init param_hidden_layer_sizes param_activation  \
0               0.000812151                      [4]         logistic   
1               0.000438419                      [8]             relu   
2               0.000144872                   [5, 4]             relu   
3                0.00900137                [9, 7, 3]             tanh   
4               0.000221655                      [4]         logistic   
5                0.00900137                      [8]         logistic   
6               0.000221655                      [6]             tanh   
7               0.000515265                      [6]             relu   
8               0.000172834                      [8]         logistic   
9                0.00013265                   [5, 7]             tanh   
10               0.00052137                [4, 9, 5]             tanh   
11               0.00670933                      [6]             tanh   
12              0.000126645                      [8]         logistic   
13               0.00900137                      [8]         logistic   
14              0.000113065                   [4, 9]             relu   
15                0.0130984                      [8]             tanh   
16              0.000172834                      [8]         logistic   
17                0.0424532                   [5, 7]             relu   
18              0.000113065                      [8]         logistic   
19              0.000172834     

In [73]:
random_search.scorer_

{'neg_mean_squared_error': make_scorer(mean_squared_error, greater_is_better=False),
 'r2': make_scorer(r2_score)}

In [74]:
# Best result of scoring parameters
print('index of best model in data frame', random_models.best_index_)
print('\nBest result of scoring parameters\n')
print(cv_results.loc[random_models.best_index_, 
                     ['mean_train_neg_mean_squared_error','mean_test_neg_mean_squared_error']],'\n')
print(cv_results.loc[random_models.best_index_, 
                     ['mean_train_r2','mean_test_r2']])
print('\nNote: Test result is on cross validation test rows')

index of best model in data frame 7

Best result of scoring parameters

mean_train_neg_mean_squared_error   -5.52761
mean_test_neg_mean_squared_error    -11.4096
Name: 7, dtype: object 

mean_train_r2    0.84975
mean_test_r2     0.67001
Name: 7, dtype: object

Note: Test result is on cross validation test rows


In [75]:
random_search.best_params_

{'solver': 'adam',
 'learning_rate_init': 0.0005152646350460735,
 'hidden_layer_sizes': [6],
 'activation': 'relu'}

In [76]:
random_search.best_estimator_

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=[6], learning_rate='constant',
             learning_rate_init=0.0005152646350460735, max_fun=15000,
             max_iter=8000, momentum=0.9, n_iter_no_change=10,
             nesterovs_momentum=True, power_t=0.5, random_state=0, shuffle=True,
             solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
             warm_start=False)

In [77]:
random_search.best_score_

0.6700097360717635

In [78]:
random_search.score(X_train, y_train)

0.8461420879445843

In [79]:
random_search.score(X_test, y_test)

0.5907545667387005

In [80]:
random_models.predict(X)

array([21.95274656, 22.1977531 , 27.36383007, 21.23750922, 16.11640121,
       21.40243843, 12.67779905, 24.35991245, 25.67408544, 20.91351916,
       21.27695953, 15.2081594 , 15.45491215, 15.67873427, 13.99235523,
       13.68451927, 13.36316612, 28.65446742, 28.67978029, 29.19053117,
       22.56958834, 16.10869864, 16.7427574 , 12.78093561, 15.95421362,
       28.40734335, 26.44685964, 27.49296062, 19.93886972, 20.43415503,
       15.11571958, 26.44968739])

# 2020-JUN-13TH

In [1]:
import pandas as pd
iris = pd.read_csv("C:/Users/Admin/Documents/Datasets/iris.csv")
iris.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa

In [2]:
import numpy as np
iris.Species = iris.Species.astype("category")
iris["Species1"] = np.repeat([0, 1, 2], 50) # for first 50 observations = 0; for next 50 = 1; for last 50 = 2

In [3]:
iris.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  \
0           1           5.1          3.5           1.4          0.2  setosa   
1           2           4.9          3.0           1.4          0.2  setosa   
2           3           4.7          3.2           1.3          0.2  setosa   
3           4           4.6          3.1           1.5          0.2  setosa   
4           5           5.0          3.6           1.4          0.2  setosa   

   Species1  
0         0  
1         0  
2         0  
3         0  
4         0

In [4]:
# Keras is built in Python and on top of TensorFlow 2.0
# Keras is a neural network library while 
# TensorFlow is the open source library for a number of tasks in machine learning.
# Both frameworks provide high-level APIs for building and training models with ease.

In [5]:
import tensorflow as tf
import keras

Using TensorFlow backend.


In [7]:
X = iris.iloc[:, :4]
y = iris.iloc[:, -1]
print(X.head())
print(y.head())
print(y.value_counts())

   Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length
0           1           5.1          3.5           1.4
1           2           4.9          3.0           1.4
2           3           4.7          3.2           1.3
3           4           4.6          3.1           1.5
4           5           5.0          3.6           1.4
0    0
1    0
2    0
3    0
4    0
Name: Species1, dtype: int32
2    50
1    50
0    50
Name: Species1, dtype: int64


In [8]:
y = pd.get_dummies(y)
y[:5]

0  1  2
0  1  0  0
1  1  0  0
2  1  0  0
3  1  0  0
4  1  0  0

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [10]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(112, 4)
(38, 4)
(112, 3)
(38, 3)


In [11]:
y_test[:5]

0  1  2
114  0  0  1
62   0  1  0
33   1  0  0
107  0  0  1
7    1  0  0

# Creating MLP in Keras

In [2]:
# Creating MLP in Keras
# Sequential function groups a linear stack of layers into a keras model
# Sequential model provides trainging and inference faetures on this model
from keras.models import Sequential
# A dense layer is just a regular layer of neurons in a neural network.
# Each neuron recieves input from all the neurons in previous layer, thus densely connected.
from keras.layers import Dense, Dropout, Activation
model = Sequential()

Using TensorFlow backend.


In [3]:
# In first Dense layer, the dimension of input layer can be given
# tensorflow:Large dropout rate: 0.8 (>0.5). 
# In TensorFlow 2.x, dropout() uses dropout rate instead of keep_prob. 
# Please ensure that this is intended.
model.add(Dense(6, input_dim=4, activation="sigmoid", name="HL1"))
model.add(Dropout(0.5))
model.add(Dense(6, activation='relu', name="HL2"))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax', name="OL"))

In [15]:
# initialized weights
print(model.weights)

[<tf.Variable 'HL1/kernel:0' shape=(4, 6) dtype=float32, numpy=
array([[-0.5099182 , -0.2782163 , -0.65879977,  0.7546493 ,  0.13363522,
         0.44102728],
       [-0.25273234,  0.14513183,  0.65977967,  0.03207397, -0.5549391 ,
         0.24491847],
       [ 0.10666811, -0.41944233,  0.08610916, -0.7293204 ,  0.36204982,
        -0.19563907],
       [-0.2670682 , -0.3420073 , -0.65178823,  0.08388233, -0.07693177,
         0.48077726]], dtype=float32)>, <tf.Variable 'HL1/bias:0' shape=(6,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0.], dtype=float32)>, <tf.Variable 'HL2/kernel:0' shape=(6, 6) dtype=float32, numpy=
array([[ 0.706804  , -0.35974544, -0.5136436 ,  0.1287576 , -0.44010514,
        -0.0410679 ],
       [-0.04632443, -0.41179004, -0.6690682 ,  0.46490806,  0.10290724,
         0.06633288],
       [ 0.25210595, -0.54829156, -0.16876441, -0.14744216, -0.22779915,
        -0.202052  ],
       [-0.17427689, -0.24586567,  0.16396457,  0.06138134, -0.18202835,
         0

In [16]:
print("Input layer shape:", model.input_shape)
print("Output layer shape:", model.output_shape)

Input layer shape: (None, 4)
Output layer shape: (None, 3)


In [17]:
# Evaluation Metrics
from keras import metrics
from keras.metrics import Precision, AUC, Recall

In [18]:
X_train.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length
61           62           5.9          3.0           4.2
92           93           5.8          2.6           4.0
112         113           6.8          3.0           5.5
2             3           4.7          3.2           1.3
141         142           6.9          3.1           5.1

In [19]:
from keras.utils import normalize
X_train = normalize(np.array(X_train), axis=1)
X_test = normalize(np.array(X_test), axis=1)

In [20]:
X_train[:5]

array([[0.9921016 , 0.09440967, 0.04800492, 0.06720688],
       [0.99675537, 0.06216324, 0.02786628, 0.0428712 ],
       [0.99666916, 0.05997655, 0.02646024, 0.04851045],
       [0.45738935, 0.71657665, 0.48788198, 0.19820205],
       [0.99794254, 0.04849157, 0.02178607, 0.0358416 ]])

# Compiling a simple model without customizing the optimizers

In [21]:
# Compile model
# Compile defines the loss function, the optimizer and the metrics
# You need a compiled model to train because training uses the loss function and the optimizer

# optimizer - name of optimizer or optimizer instance:'SGD','RMSprop','Adam'

# loss - name of objective function or objective function or `Loss` instance:
# Classification - binary_crossentropy, categorical_crossentropy
# Regression - mean_squared_error, mean_absolute_error, mean_absolute_percentage_error

# metrics - List of metrics to be evaluated by the model during training and testing

model.compile(loss='categorical_crossentropy', 
              optimizer='Adam',
              metrics=['accuracy', tf.keras.metrics.AUC(), tf.keras.metrics.Precision(),
                      tf.keras.metrics.Recall()])

# Defining optimizers with learning_rate values

In [22]:
# Alternatively, we can separately define optimizers
opt_SGD = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9, name="SGD")
# rho is beta of RMSprop
opt_RMSprop = tf.keras.optimizers.RMSprop(learning_rate=0.001, rho=0.9, momentum=0.9, 
                                          epsilon=1e-07, name="RMSprop")
opt_Adam = tf.keras.optimizers.Adam(learning_rate=0.01, beta_1=0.9, beta_2=0.999, 
                                    epsilon=1e-07, name="Adam")

# Defining Learning rate schedules -- going to use after defining

In [23]:
# We can specify learning rate schedules
# a)exponential decay schedule
# initial_learning_rate * decay_rate ^ (step / decay_steps)
# If staircase = True then (step / decay_steps) will be integer
initial_learning_rate = 0.1
lr_schedule1 = tf.keras.optimizers.schedules.ExponentialDecay(
                initial_learning_rate,
                decay_steps=100000,
                decay_rate=0.96,
                staircase=True)

# b) Polynomial Decay
# (initial_learning_rate - end_learning_rate)*(1 - step/decay_steps)^(power) + end_learning_rate

starter_learning_rate = 0.1
end_learning_rate = 0.01
decay_steps = 10000
lr_schedule2 = tf.keras.optimizers.schedules.PolynomialDecay(
                starter_learning_rate,
                decay_steps,
                end_learning_rate,
                power=0.5)

# c)Inverse Time Decay
# initial_learning_rate / (1 + decay_rate * step / decay_step)

initial_learning_rate = 0.1
decay_steps = 1.0
decay_rate = 0.5
lr_schedule3 = tf.keras.optimizers.schedules.InverseTimeDecay(
                  initial_learning_rate, 
                  decay_steps, 
                  decay_rate)

# Defining Optimizers with learning rate schedules instead of just learning_rate values

In [ ]:
# We can separately define optimizers with learning rate schedule defined
opt_SGD1 = tf.keras.optimizers.SGD(learning_rate=lr_schedule1, momentum=0.9, name="SGD")
# rho is beta of RMSprop
opt_RMSprop1 = tf.keras.optimizers.RMSprop(learning_rate=lr_schedule2, rho=0.9, momentum=0.9, 
                                          epsilon=1e-07, name="RMSprop")
opt_Adam1 = tf.keras.optimizers.Adam(learning_rate=lr_schedule3, beta_1=0.9, beta_2=0.999, 
                                    epsilon=1e-07, name="Adam")

# Compile Model using defined customized optimizers

In [51]:
# compile model with with defined optimizers
model.compile(loss='categorical_crossentropy', 
              optimizer=opt_SGD1,
              metrics=['accuracy', tf.keras.metrics.AUC(), tf.keras.metrics.Precision(),
                      tf.keras.metrics.Recall()])

In [53]:
# Fit the model
# 1 eopch = 1 passs through the entire training set
# batch_size - for mini-batch gradient descent
# validation_split: Fraction of the training data to be used as validation data.
# The model will set apart this fraction of the training data, will not train on it, 
# and will evaluate the loss and any model metrics on this data at the end of each epoch.

keras_do_model= model.fit(X_train, y_train, 
                          epochs=500, batch_size = 20, 
                          validation_split = 0.2, verbose = False)

In [54]:
preds = model.predict(X_test)
print(preds[:5])

[[0.31332493 0.26344475 0.42323038]
 [0.31332493 0.26344475 0.42323038]
 [0.31332493 0.26344475 0.42323038]
 [0.31332493 0.26344475 0.42323038]
 [0.31332493 0.26344475 0.42323038]]


In [55]:
# evaluate the model
# Returns the loss value & metrics values for the model in test mode
scores_train = model.evaluate(X_train, y_train)
print("Training Metrics: \n ", model.metrics_names[1], scores_train[1], "\n ",
      model.metrics_names[2], scores_train[2], "\n ",
      model.metrics_names[3], scores_train[3], "\n ",
      model.metrics_names[4], scores_train[4], "\n ")
scores_test = model.evaluate(X_test, y_test)
print("Test Metrics: \n ", model.metrics_names[1], scores_test[1], "\n ",
      model.metrics_names[2], scores_test[2], "\n ",
      model.metrics_names[3], scores_test[3], "\n ",
      model.metrics_names[4], scores_test[4], "\n ")

112/112 [==============================] - 0s 89us/step
Training Metrics: 
  accuracy 0.3660714328289032 
  auc_4 0.5248908400535583 
  precision_4 0.0 
  recall_4 0.0 
 
38/38 [==============================] - 0s 131us/step
Test Metrics: 
  accuracy 0.2368421107530594 
  auc_4 0.5248249173164368 
  precision_4 0.0 
  recall_4 0.0 
 


# Model Summary

In [58]:
model.summary()
# Note that the Input Layer is not displayed as part of model layers, since it isn't a layer.

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
HL1 (Dense)                  (None, 6)                 30        
_________________________________________________________________
dropout_3 (Dropout)          (None, 6)                 0         
_________________________________________________________________
HL2 (Dense)                  (None, 6)                 42        
_________________________________________________________________
dropout_4 (Dropout)          (None, 6)                 0         
_________________________________________________________________
OL (Dense)                   (None, 3)                 21        
Total params: 93
Trainable params: 93
Non-trainable params: 0
_________________________________________________________________


In [59]:
# Why is output shape = (None, 6) in above summary?? i.e. why None

In [60]:
from ann_visualizer.visualize import ann_viz
ann_viz(model, title="Shallow Neural Network", view = True)

In [61]:
# Regularization
# add to dense layer: 
# for L2 regularization: kernel_regularizer=tf.keras.regularizers.l2(l=0.1)
# for L1 regularization: kernel_regularizer=tf.keras.regularizers.l1(l=0.1)

# Regularization

In [3]:
model = Sequential()
model.add(Dense(6, input_dim=4, activation='sigmoid',
                kernel_regularizer=tf.keras.regularizers.l2(l=0.1),name="HL1"))
model.add(Dropout(0.5))
model.add(Dense(6, activation='relu', 
                kernel_regularizer=tf.keras.regularizers.l2(l=0.1), name="HL2"))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax', name="OL"))

NameError: name 'Sequential' is not defined

In [64]:
model.compile(loss='categorical_crossentropy', 
              optimizer='Adam',
              metrics=['accuracy', tf.keras.metrics.AUC(), tf.keras.metrics.Precision(),
                      tf.keras.metrics.Recall()])

In [65]:
keras_do_reg_model= model.fit(X_train, y_train, 
                          epochs=500, batch_size = 20, 
                          validation_split = 0.1, verbose = False)

In [66]:
# evaluate the model
# Returns the loss value & metrics values for the model in test mode
scores_train = model.evaluate(X_train, y_train)
print("Training Metrics: \n ", model.metrics_names[1], scores_train[1], "\n ",
      model.metrics_names[2], scores_train[2], "\n ",
      model.metrics_names[3], scores_train[3], "\n ",
      model.metrics_names[4], scores_train[4], "\n ")
scores_test = model.evaluate(X_test, y_test)
print("Test Metrics: \n ", model.metrics_names[1], scores_test[1], "\n ",
      model.metrics_names[2], scores_test[2], "\n ",
      model.metrics_names[3], scores_test[3], "\n ",
      model.metrics_names[4], scores_test[4], "\n ")

112/112 [==============================] - 0s 189us/step
Training Metrics: 
  accuracy 0.3660714328289032 
  auc_5 0.5279216766357422 
  precision_5 0.26966291666030884 
  recall_5 0.0004279906861484051 
 
38/38 [==============================] - 0s 131us/step
Test Metrics: 
  accuracy 0.2368421107530594 
  auc_5 0.5278059244155884 
  precision_5 0.26966291666030884 
  recall_5 0.00042744935490190983 
 


In [67]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
HL1 (Dense)                  (None, 6)                 30        
_________________________________________________________________
dropout_7 (Dropout)          (None, 6)                 0         
_________________________________________________________________
HL2 (Dense)                  (None, 6)                 42        
_________________________________________________________________
dropout_8 (Dropout)          (None, 6)                 0         
_________________________________________________________________
OL (Dense)                   (None, 3)                 21        
Total params: 93
Trainable params: 93
Non-trainable params: 0
_________________________________________________________________


In [50]:
ann_viz(model, title="Shallow Neural Network", view = True)

# Batch normalization

In [68]:
from keras.layers.normalization import BatchNormalization

In [69]:
# Trainable = True: the variables will be marked as trainable
batch_norm = tf.keras.layers.BatchNormalization(
                axis=1,
                momentum=0.99,
                epsilon=0.001,
                center=True,
                scale=True,
                beta_initializer="zeros",
                gamma_initializer="ones",
                moving_mean_initializer="zeros",
                moving_variance_initializer="ones",
                trainable=True)

In [70]:
model = Sequential()
model.add(Dense(6, input_dim=4, activation='sigmoid',
                kernel_regularizer=tf.keras.regularizers.l2(l=0.01),name="HL1"))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(6, activation='relu', 
                kernel_regularizer=tf.keras.regularizers.l2(l=0.01), name="HL2"))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax', name="OL"))

In [71]:
model.compile(loss='categorical_crossentropy', 
              optimizer='Adam',
              metrics=['accuracy', tf.keras.metrics.AUC(), tf.keras.metrics.Precision(),
                      tf.keras.metrics.Recall()])

In [72]:
keras_do_bn_reg_model= model.fit(X_train, y_train, 
                                 epochs=500, batch_size = 20, 
                                 validation_split = 0.1, verbose = False)

In [73]:
# evaluate the model
# Returns the loss value & metrics values for the model in test mode
scores_train = model.evaluate(X_train, y_train)
print("Training Metrics: \n ", model.metrics_names[1], scores_train[1], "\n ",
      model.metrics_names[2], scores_train[2], "\n ",
      model.metrics_names[3], scores_train[3], "\n ",
      model.metrics_names[4], scores_train[4], "\n ")
scores_test = model.evaluate(X_test, y_test)
print("Test Metrics: \n ", model.metrics_names[1], scores_test[1], "\n ",
      model.metrics_names[2], scores_test[2], "\n ",
      model.metrics_names[3], scores_test[3], "\n ",
      model.metrics_names[4], scores_test[4], "\n ")

112/112 [==============================] - 0s 107us/step
Training Metrics: 
  accuracy 0.9464285969734192 
  auc_6 0.9147660136222839 
  precision_6 0.8004037141799927 
  recall_6 0.66461580991745 
 
38/38 [==============================] - 0s 131us/step
Test Metrics: 
  accuracy 0.8947368264198303 
  auc_6 0.9148874282836914 
  precision_6 0.8006412982940674 
  recall_6 0.6648886203765869 
 


In [74]:
model.summary()
# In Batch Normalization layer 12 parameters are trainable 
# and 12 are not trainable. Trainable parameters are gamma and beta
# Not trainable are running weighted mean and standard deviation

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
HL1 (Dense)                  (None, 6)                 30        
_________________________________________________________________
batch_normalization_1 (Batch (None, 6)                 24        
_________________________________________________________________
dropout_9 (Dropout)          (None, 6)                 0         
_________________________________________________________________
HL2 (Dense)                  (None, 6)                 42        
_________________________________________________________________
batch_normalization_2 (Batch (None, 6)                 24        
_________________________________________________________________
dropout_10 (Dropout)         (None, 6)                 0         
_________________________________________________________________
OL (Dense)                   (None, 3)                

In [ ]:
# ann_viz is not designed for batch_norm
# ann_viz(model, title="Shallow Neural Network", view = True)