In [1]:
# Shallow Neural Network

In [2]:
# import libraries
import pandas as pd
import numpy as np

import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib notebook

In [3]:
# prepare data
# IRIS dataset
iris = pd.read_csv('C:/Users/Admin/Documents/Datasets/iris.csv')
iris['Species'] = iris['Species'].astype('category')
iris['Species1'] = np.repeat([0,1,2],50)
print(iris.head())

   Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  \
0           1           5.1          3.5           1.4          0.2  setosa   
1           2           4.9          3.0           1.4          0.2  setosa   
2           3           4.7          3.2           1.3          0.2  setosa   
3           4           4.6          3.1           1.5          0.2  setosa   
4           5           5.0          3.6           1.4          0.2  setosa   

   Species1  
0         0  
1         0  
2         0  
3         0  
4         0  


In [4]:
X = iris.iloc[:, :4]
y = iris.iloc[:, -1]

print(X.head())
print(y.value_counts())


   Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length
0           1           5.1          3.5           1.4
1           2           4.9          3.0           1.4
2           3           4.7          3.2           1.3
3           4           4.6          3.1           1.5
4           5           5.0          3.6           1.4
2    50
1    50
0    50
Name: Species1, dtype: int64


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=0)

In [6]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(112, 4)
(38, 4)
(112,)
(38,)


In [7]:
# import Neural Network libraries (MLP - MultiLayerPerceptron)
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [8]:
# Classification
# activation : ('logistic', 'tanh', 'relu','identity') : Activation function for hidden layer
nnclf = MLPClassifier(solver = 'sgd',
                    activation = 'logistic',
                    hidden_layer_sizes = (3),
                    learning_rate_init = 0.05,
                    max_iter = 2000,
                    random_state=0).fit(X_train, y_train)

In [9]:
print('Iris Data Set')
print('Accuracy of NN Classifier on training set: {:.3f}'
    .format(nnclf.score(X_train, y_train)))
print('Accuracy of NN Classifier on test set: {:.3f}'
    .format(nnclf.score(X_test, y_test)))

Iris Data Set
Accuracy of NN Classifier on training set: 0.366
Accuracy of NN Classifier on test set: 0.237


In [10]:
print(nnclf.predict_proba(X_test[:5]))
print(nnclf.predict(X_test[:5]))

[[0.3284128  0.30845719 0.36313001]
 [0.32841278 0.30845724 0.36312998]
 [0.32841199 0.30846554 0.36312247]
 [0.3284128  0.30845719 0.36313001]
 [0.32819413 0.31067625 0.36112962]]
[2 2 2 2 2]


In [11]:
print("Classes for Y: ", nnclf.classes_)
print("Activation function at Output layer: ", nnclf.out_activation_)
print("No of Layers: ", nnclf.n_layers_)
print("No of Outputs: ", nnclf.n_outputs_)
print("No of iterations for convergence: ", nnclf.n_iter_)
print(" \n Weights matrix: \n ", nnclf.coefs_)
print(" \n Bias: \n ", nnclf.intercepts_)

Classes for Y:  [0 1 2]
Activation function at Output layer:  softmax
No of Layers:  3
No of Outputs:  3
No of iterations for convergence:  35
 
 Weights matrix: 
  [array([[-0.61777099,  0.21130142,  0.19592142],
       [-0.16983377, -0.10165183,  0.21600137],
       [-0.21036227,  0.40526729,  0.53640092],
       [-0.19335158,  0.30606876,  0.04828937]]), array([[-0.34931499, -0.56072659,  0.26337963],
       [ 0.36625578,  0.36356711,  0.5712632 ],
       [ 0.38407365, -0.10508861,  0.34589334]])]
 
 Bias: 
  [array([ 0.02928363,  0.45090112, -0.44633303]), array([-0.3512857 ,  0.07787694, -0.41762324])]


In [12]:
# keras

In [13]:
# Keras is built in Python and on top of TensorFlow 2.0
# Keras is a neural network library while TensorFlow is the open source library
# for a number of tasks in machine learning.
# Both frameworks provide high-level APIs for building and training models with ease.

In [14]:
import tensorflow as tf
import keras

Using TensorFlow backend.


In [15]:
# Createing MLP in Keras
# Sequential function groups a linear stack of layers into a keras model
# Sequential model provides training and inference features on this model
from keras.models import Sequential
# A dense layer is just a regular layer of neurons in a neural network.
# Each neuron recieves input from all the neurons in the previous layer,
# thus densely connected.
from keras.layers import Dense

In [16]:
# create model
model = Sequential()

In [17]:
# In first Dense layer, the dimension of input layer can be given
model.add(Dense(6, input_dim=4, activation='sigmoid', name="HL1"))
model.add(Dense(3, activation='relu', name="HL2"))
model.add(Dense(3, activation='softmax', name="OL"))

In [18]:
# initialized weights
print(model.weights)

[<tf.Variable 'HL1/kernel:0' shape=(4, 6) dtype=float32, numpy=
array([[-0.72889197,  0.4188851 , -0.13175553, -0.48178545,  0.05715513,
         0.08885056],
       [-0.4779388 ,  0.6346241 , -0.5636107 , -0.15083945,  0.42110074,
         0.49004853],
       [-0.22889262,  0.7230065 , -0.6518217 ,  0.5385817 , -0.26785547,
         0.00367177],
       [ 0.43679154,  0.6357167 , -0.6038618 , -0.61694425, -0.44332233,
         0.59893847]], dtype=float32)>, <tf.Variable 'HL1/bias:0' shape=(6,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0.], dtype=float32)>, <tf.Variable 'HL2/kernel:0' shape=(6, 3) dtype=float32, numpy=
array([[ 0.63694227, -0.44813284, -0.31393558],
       [-0.13149726, -0.47988632,  0.4235146 ],
       [-0.7211152 ,  0.10565037, -0.12428987],
       [-0.01934552, -0.0529024 ,  0.4203701 ],
       [ 0.7256725 , -0.22609377, -0.07865328],
       [ 0.19930923, -0.4635601 , -0.3505166 ]], dtype=float32)>, <tf.Variable 'HL2/bias:0' shape=(3,) dtype=float32, numpy=arra

In [19]:
print("Input layer shape:", model.input_shape)
print("Output layer shape:", model.output_shape)


Input layer shape: (None, 4)
Output layer shape: (None, 3)


In [20]:
from keras import metrics
from keras.metrics import Precision, AUC, Recall

In [21]:
# Compile model
# Compile defines the loss function, the optimizer and the metrics
# You need a compiled model to train because training uses the loss function and the optimizer
model.compile(loss='mse', optimizer='sgd',
              metrics=['accuracy', tf.keras.metrics.AUC(), tf.keras.metrics.Precision(),
                      tf.keras.metrics.Recall()])

In [22]:
X.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length
0           1           5.1          3.5           1.4
1           2           4.9          3.0           1.4
2           3           4.7          3.2           1.3
3           4           4.6          3.1           1.5
4           5           5.0          3.6           1.4

In [23]:
y = pd.get_dummies(y)
y[:5]

0  1  2
0  1  0  0
1  1  0  0
2  1  0  0
3  1  0  0
4  1  0  0

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [25]:
y_test[:5]

0  1  2
114  0  0  1
62   0  1  0
33   1  0  0
107  0  0  1
7    1  0  0

In [26]:
# Fit the model
model.fit(X_train, y_train, epochs=500, verbose = True)

Epoch 1/500
112/112 [==============================] - 0s 1ms/step - loss: 0.2340 - accuracy: 0.3304 - auc: 0.4254 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 2/500
112/112 [==============================] - 0s 80us/step - loss: 0.2338 - accuracy: 0.3304 - auc: 0.4324 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 3/500
112/112 [==============================] - 0s 125us/step - loss: 0.2336 - accuracy: 0.3304 - auc: 0.4279 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 4/500
112/112 [==============================] - 0s 98us/step - loss: 0.2334 - accuracy: 0.3304 - auc: 0.4295 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 5/500
112/112 [==============================] - 0s 116us/step - loss: 0.2332 - accuracy: 0.3304 - auc: 0.4246 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 6/500
112/112 [==============================] - 0s 80us/step - loss: 0.2330 - accuracy: 0.3304 - auc: 0.4320 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 7/500
112/112 [============

112/112 [==============================] - 0s 125us/step - loss: 0.2274 - accuracy: 0.3304 - auc: 0.4716 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 51/500
112/112 [==============================] - 0s 107us/step - loss: 0.2273 - accuracy: 0.3304 - auc: 0.4720 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 52/500
112/112 [==============================] - 0s 116us/step - loss: 0.2272 - accuracy: 0.3304 - auc: 0.4726 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 53/500
112/112 [==============================] - 0s 116us/step - loss: 0.2271 - accuracy: 0.3304 - auc: 0.4731 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 54/500
112/112 [==============================] - 0s 116us/step - loss: 0.2271 - accuracy: 0.3304 - auc: 0.4739 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 55/500
112/112 [==============================] - 0s 116us/step - loss: 0.2270 - accuracy: 0.3304 - auc: 0.4742 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 56/500
112/112 [=============

112/112 [==============================] - 0s 89us/step - loss: 0.2245 - accuracy: 0.2946 - auc: 0.4895 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 101/500
112/112 [==============================] - 0s 89us/step - loss: 0.2245 - accuracy: 0.2946 - auc: 0.4896 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 102/500
112/112 [==============================] - 0s 89us/step - loss: 0.2245 - accuracy: 0.2946 - auc: 0.4897 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 103/500
112/112 [==============================] - 0s 116us/step - loss: 0.2244 - accuracy: 0.2946 - auc: 0.4898 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 104/500
112/112 [==============================] - 0s 134us/step - loss: 0.2244 - accuracy: 0.2946 - auc: 0.4901 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 105/500
112/112 [==============================] - 0s 116us/step - loss: 0.2244 - accuracy: 0.2946 - auc: 0.4902 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 106/500
112/112 [==========

112/112 [==============================] - 0s 125us/step - loss: 0.2234 - accuracy: 0.2232 - auc: 0.4915 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 149/500
112/112 [==============================] - 0s 107us/step - loss: 0.2234 - accuracy: 0.2232 - auc: 0.4914 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 150/500
112/112 [==============================] - 0s 125us/step - loss: 0.2234 - accuracy: 0.2232 - auc: 0.4914 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 151/500
112/112 [==============================] - 0s 125us/step - loss: 0.2233 - accuracy: 0.2143 - auc: 0.4913 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 152/500
112/112 [==============================] - 0s 89us/step - loss: 0.2233 - accuracy: 0.2054 - auc: 0.4911 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 153/500
112/112 [==============================] - 0s 98us/step - loss: 0.2233 - accuracy: 0.1964 - auc: 0.4911 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 154/500
112/112 [=========

112/112 [==============================] - 0s 80us/step - loss: 0.2228 - accuracy: 0.3661 - auc: 0.4922 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 198/500
112/112 [==============================] - 0s 167us/step - loss: 0.2228 - accuracy: 0.3661 - auc: 0.4922 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 199/500
112/112 [==============================] - 0s 107us/step - loss: 0.2228 - accuracy: 0.3661 - auc: 0.4924 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 200/500
112/112 [==============================] - 0s 116us/step - loss: 0.2228 - accuracy: 0.3661 - auc: 0.4925 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 201/500
112/112 [==============================] - 0s 116us/step - loss: 0.2228 - accuracy: 0.3661 - auc: 0.4926 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 202/500
112/112 [==============================] - 0s 116us/step - loss: 0.2228 - accuracy: 0.3661 - auc: 0.4927 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 203/500
112/112 [========

112/112 [==============================] - 0s 89us/step - loss: 0.2225 - accuracy: 0.3661 - auc: 0.4972 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 247/500
112/112 [==============================] - 0s 125us/step - loss: 0.2225 - accuracy: 0.3661 - auc: 0.4974 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 248/500
112/112 [==============================] - 0s 125us/step - loss: 0.2225 - accuracy: 0.3661 - auc: 0.4975 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 249/500
112/112 [==============================] - 0s 107us/step - loss: 0.2225 - accuracy: 0.3661 - auc: 0.4976 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 250/500
112/112 [==============================] - 0s 116us/step - loss: 0.2225 - accuracy: 0.3661 - auc: 0.4977 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 251/500
112/112 [==============================] - 0s 98us/step - loss: 0.2225 - accuracy: 0.3661 - auc: 0.4978 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 252/500
112/112 [=========

112/112 [==============================] - 0s 98us/step - loss: 0.2223 - accuracy: 0.3661 - auc: 0.5016 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 297/500
112/112 [==============================] - 0s 98us/step - loss: 0.2223 - accuracy: 0.3661 - auc: 0.5017 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 298/500
112/112 [==============================] - 0s 89us/step - loss: 0.2223 - accuracy: 0.3661 - auc: 0.5017 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 299/500
112/112 [==============================] - 0s 80us/step - loss: 0.2223 - accuracy: 0.3661 - auc: 0.5019 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 300/500
112/112 [==============================] - 0s 107us/step - loss: 0.2223 - accuracy: 0.3661 - auc: 0.5019 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 301/500
112/112 [==============================] - 0s 107us/step - loss: 0.2223 - accuracy: 0.3661 - auc: 0.5020 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 302/500
112/112 [===========

Epoch 345/500
112/112 [==============================] - 0s 89us/step - loss: 0.2222 - accuracy: 0.3661 - auc: 0.5045 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 346/500
112/112 [==============================] - 0s 80us/step - loss: 0.2222 - accuracy: 0.3661 - auc: 0.5045 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 347/500
112/112 [==============================] - 0s 71us/step - loss: 0.2222 - accuracy: 0.3661 - auc: 0.5046 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 348/500
112/112 [==============================] - 0s 98us/step - loss: 0.2222 - accuracy: 0.3661 - auc: 0.5046 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 349/500
112/112 [==============================] - 0s 107us/step - loss: 0.2222 - accuracy: 0.3661 - auc: 0.5047 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 350/500
112/112 [==============================] - 0s 98us/step - loss: 0.2222 - accuracy: 0.3661 - auc: 0.5047 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 351/500
112/112

112/112 [==============================] - 0s 80us/step - loss: 0.2222 - accuracy: 0.3661 - auc: 0.5065 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 393/500
112/112 [==============================] - 0s 107us/step - loss: 0.2222 - accuracy: 0.3661 - auc: 0.5065 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 394/500
112/112 [==============================] - 0s 107us/step - loss: 0.2222 - accuracy: 0.3661 - auc: 0.5066 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 395/500
112/112 [==============================] - 0s 107us/step - loss: 0.2222 - accuracy: 0.3661 - auc: 0.5066 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 396/500
112/112 [==============================] - 0s 116us/step - loss: 0.2222 - accuracy: 0.3661 - auc: 0.5066 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 397/500
112/112 [==============================] - 0s 125us/step - loss: 0.2222 - accuracy: 0.3661 - auc: 0.5066 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 398/500
112/112 [========

112/112 [==============================] - 0s 98us/step - loss: 0.2221 - accuracy: 0.3661 - auc: 0.5081 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 443/500
112/112 [==============================] - 0s 89us/step - loss: 0.2221 - accuracy: 0.3661 - auc: 0.5082 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 444/500
112/112 [==============================] - 0s 89us/step - loss: 0.2221 - accuracy: 0.3661 - auc: 0.5082 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 445/500
112/112 [==============================] - 0s 116us/step - loss: 0.2221 - accuracy: 0.3661 - auc: 0.5082 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 446/500
112/112 [==============================] - 0s 125us/step - loss: 0.2221 - accuracy: 0.3661 - auc: 0.5082 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 447/500
112/112 [==============================] - 0s 107us/step - loss: 0.2221 - accuracy: 0.3661 - auc: 0.5082 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 448/500
112/112 [==========

112/112 [==============================] - 0s 98us/step - loss: 0.2221 - accuracy: 0.3661 - auc: 0.5089 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 492/500
112/112 [==============================] - 0s 107us/step - loss: 0.2221 - accuracy: 0.3661 - auc: 0.5090 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 493/500
112/112 [==============================] - 0s 80us/step - loss: 0.2221 - accuracy: 0.3661 - auc: 0.5090 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 494/500
112/112 [==============================] - 0s 107us/step - loss: 0.2221 - accuracy: 0.3661 - auc: 0.5089 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 495/500
112/112 [==============================] - 0s 71us/step - loss: 0.2221 - accuracy: 0.3661 - auc: 0.5090 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 496/500
112/112 [==============================] - 0s 71us/step - loss: 0.2221 - accuracy: 0.3661 - auc: 0.5090 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 497/500
112/112 [===========

In [27]:
preds = model.predict(X_test)
print(preds[:5])

[[0.33276    0.30165124 0.36558878]
 [0.33275953 0.3016519  0.36558864]
 [0.3327043  0.30172533 0.36557037]
 [0.33276    0.30165124 0.36558878]
 [0.3277006  0.30842155 0.36387783]]


In [28]:
# evaluate the model
# Returns the loss value & metrics values for the model in test mode
scores_train = model.evaluate(X_train, y_train)
print("Training Metrics: \n ", model.metrics_names[1], scores_train[1], "\n ",
      model.metrics_names[2], scores_train[2], "\n ",
      model.metrics_names[3], scores_train[3], "\n ",
      model.metrics_names[4], scores_train[4], "\n ")
scores_test = model.evaluate(X_test, y_test)
print("Test Metrics: \n ", model.metrics_names[1], scores_test[1], "\n ",
      model.metrics_names[2], scores_test[2], "\n ",
      model.metrics_names[3], scores_test[3], "\n ",
      model.metrics_names[4], scores_test[4], "\n ")

112/112 [==============================] - 0s 579us/step
Training Metrics: 
  accuracy 0.3660714328289032 
  auc 0.5090785622596741 
  precision 0.0 
  recall 0.0 
 
38/38 [==============================] - 0s 105us/step
Test Metrics: 
  accuracy 0.2368421107530594 
  auc 0.509012758731842 
  precision 0.0 
  recall 0.0 
 


In [29]:
model.summary()
# Note that the Input Layer is not displayed as part of model layers, since it isn't a layer.


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
HL1 (Dense)                  (None, 6)                 30        
_________________________________________________________________
HL2 (Dense)                  (None, 3)                 21        
_________________________________________________________________
OL (Dense)                   (None, 3)                 12        
Total params: 63
Trainable params: 63
Non-trainable params: 0
_________________________________________________________________


In [30]:
from ann_visualizer.visualize import ann_viz;
ann_viz(model, title="Shallow Neural Network", view = True)